// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using Palidzibas_servissML.Model;

namespace Palidzibas_servissML.Model
{
    // Klase, kas apraksta modeïa patçriòu
    public class ConsumeModel
    {
        // Statiskais objekts, kas uzglabâ slçgtu prognozçðanas dzinçju
        private static Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictionEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(CreatePredictionEngine);

        // Metode, lai patçrçtu modeli jûsu lietotnç
        public static ModelOutput Predict(ModelInput input)
        {
            // Veic prognozi, izmantojot sagatavoto prognozçðanas dzinçju
            ModelOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        // Metode, kas veido prognozçðanas dzinçju
        public static PredictionEngine<ModelInput, ModelOutput> CreatePredictionEngine()
        {
            // Izveido jaunu ML kontekstu
            MLContext mlContext = new MLContext();

            // Ielâdç modeli un izveido prognozçðanas dzinçju
            string modelPath = @"Z:\Palidzibas_serviss\Palidzibas_servissML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            return predEngine;
        }
    }
}

