// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace Palidzibas_servissML.Model
{
    // Klase, kas apraksta modeïa izvadi
    public class ModelOutput
    {
        // Masîvs, kas satur rezultâtus jeb varbûtîbas katrâ no kategorijâm
        public float[] Score { get; set; }
    }
}
